name: Deploy to EC2 and Push to S3

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


# trnsfering files to ec2 
    - name: Deploy server to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: | 
        echo "ENVS ----- --- "
        echo $EC2_HOST
        echo $EC2_USER
        echo $EC2_KEY
        scp -i $EC2_KEY -r ./app-01 $EC2_USER@$EC2_HOST:/home/ubuntu/nodejs-app
# ssh -i $EC2_KEY $EC2_USER@$EC2_HOST "cd /home/ubuntu/nodejs-app/server && npm install && pm2 restart all"


    # - name: Upload server build to S3
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: ${{ secrets.AWS_REGION }}
    #     S3_BUCKET: ${{ secrets.S3_BUCKET }}

    #   run: |
    #     VERSION=$(jq -r .version server/package.json)
    #     aws s3 cp ./server s3://$S3_BUCKET/server-node-app-v$VERSION/ --recursive
