name: Deploy to EC2 and Push to S3

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # Decode EC2 Key
    - name: Decode EC2 Key
      run: echo ${{ secrets.EC2_KEY }} | base64 --decode > ec2_key.pem

    # Add EC2 host to known hosts
    - name: Add EC2 host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy server to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        scp -i ec2_key.pem -r ./server $EC2_USER@$EC2_HOST:/home/ubuntu/nodejs-app

    - name: Cleanup
      run: rm -f ec2_key.pem
