name: Deploy to EC2 and Push to S3

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Backend deployment steps
    # - name: Install dependencies for the server
    #   working-directory: ./app-01
    #   run: npm install

    # - name: Run server tests
    #   working-directory: ./server
    #   run: npm test

    # - name: Build the server
    #   working-directory: ./server
    #   run: npm run build

    - name: Get server version from package.json
      id: get_version
      working-directory: ./server
      run: | 
        echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
        echo "Application version"
        VERSION=$(jq -r .version package.json)
        echo $VERSION


# trnsfering files to ec2 
    - name: Deploy server to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
        
      run: |
        scp -i $EC2_KEY -r ./server $EC2_USER@$EC2_HOST:/home/ubuntu/nodejs-app
# ssh -i $EC2_KEY $EC2_USER@$EC2_HOST "cd /home/ubuntu/nodejs-app/server && npm install && pm2 restart all"


    # - name: Upload server build to S3
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: ${{ secrets.AWS_REGION }}
    #     S3_BUCKET: ${{ secrets.S3_BUCKET }}

    #   run: |
    #     VERSION=$(jq -r .version server/package.json)
    #     aws s3 cp ./server s3://$S3_BUCKET/server-node-app-v$VERSION/ --recursive
